prompt_order = [
    "username",
    "hostname",
    "kubernetes",
    "directory",
    "time",
    "git_branch",
    # "git_commit",
    # "git_state",
    # "git_status",
    # "hg_branch",
    "package",
    "dotnet",
    "golang",
    "java",
    "nodejs",
    "php",
    "python",
    "ruby",
    "rust",
    "terraform",
    "nix_shell",
    "conda",
    "memory_usage",
    "aws",
    "env_var",
    "cmd_duration",
    "line_break",
    "jobs",
    "battery",
    "character",
]

[username]
show_always=true
style_user="yellow"
style_root="yellow"

[hostname]
style="red"

[directory]
style="green"
truncation_length = 3

[git_branch]
style="fg:#ebd334"

[git_status]
style="fg:e07798"

[character]
symbol = "$"
style_success="bold white"
style_failure="bold red"

[time]
disabled = false
style="purple"

[jobs]
symbol = "+ "
threshold = 4

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

[python]
disabled = true

[package]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[nodejs]
disabled = true

[java]
disabled = true

[golang]
disabled = true

[aws]
disabled = true
