prompt_order = [
    "username",
    "hostname",
    "kubernetes",
    "directory",
    "time",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "hg_branch",
    "package",
    "dotnet",
    "golang",
    "java",
    "nodejs",
    "php",
    "python",
    "ruby",
    "rust",
    "terraform",
    "nix_shell",
    "conda",
    "memory_usage",
    "aws",
    "env_var",
    "cmd_duration",
    "line_break",
    "jobs",
    "battery",
    "character",
]

[username]
show_always=true
style_user="bold fg:#3477eb"
style_root="bold yellow"

[hostname]
style="fg:#34d3eb"

[directory]
style="fg:#34eb80"
truncation_length = 3

[git_branch]
style="bold fg:#ebd334"

[git_status]
style="bold fg:e07798"

[character]
symbol = "$"
style_success="bold white"
style_failure="bold red"

[time]
disabled = false
style="bold fg:#34ebdc"

[jobs]
symbol = "+ "
threshold = 4

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"


